"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ImportBsJS from "@/app/components/ImportBsJS";
import UserProvider from "./Contexts/UserContext";
import TicketProvider from "./Contexts/TicketContext";
import ChairProvider from "./Contexts/ChairContext";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ImportBsJS />
        <UserProvider>
          <TicketProvider>
            <ChairProvider>
              <div>{children}</div>
            </ChairProvider>
          </TicketProvider>
        </UserProvider>
      </body>
    </html>
  );
}
